# executor: slurm
# jobs: 40
# default-resources:
#     slurm_partition: "SVC"
#     slurm_extra: ""
executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/{wildcards.project}/slurm &&
  sbatch
    --partition=SVC
    --cpus-per-task={threads}
    --job-name={rule}
    --output=logs/{wildcards.project}/slurm/{wildcards.sample}_{rule}.%N.%j.out
default-resources:
  - partition=SVC
latency-wait: 60
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True