resources:
  hg19:
    REFFA: "/Users/ZYL/Documents/Project/Github/clinwdl/snakemake/WES/data/ucsc.hg19.fasta"
    REFFA_DICT: "/Users/ZYL/Documents/Project/Github/clinwdl/snakemake/WES/data/ucsc.hg19.fasta"
    BED_GENOME: "/public/home/lijf/projects/clinrep/meta/bed/genome/hg19/genome.bed"
    BED_PANEL: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_al/IDT-100.Targeted.hg19.bed"
    BED_PANEL_MM: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_mm/MM_panel_genes.Targeted.hg19_20211012.final.bed"
    BED_PANEL_EXTEND: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_al/IDT-100.Targeted.hg19.extend.bed"
    BED_PANEL_EXTEND_MM: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_mm/MM_panel_genes.Targeted.hg19_20211012.final.extend.bed"
    BIAT_PANEL: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_al/IDT-100.Targeted.hg19.interval_list"
    BIAT_PANEL_MM: "/public/home/lijf/projects/clinrep/meta/bed/panel/hg19_mm/MM_panel_genes.Targeted.hg19_20211012.final.interval_list"
  hg38:
    REFFA: "/public/home/lijf/env/genome/broad/hg38-v2/Homo_sapiens_assembly38.fasta"
    REFFA_DICT: "/public/home/lijf/env/genome/broad/hg38-v2/Homo_sapiens_assembly38.dict"
    BED_GENOME_38: "/public/home/lijf/projects/clinrep/meta/bed/genome/hg38/genome.bed"
    GENECODE_HG38: "/public/home/lijf/env/genome/gencode/hg38/v38"
    GENECODE_HG38_v38_GTF: "/public/home/lijf/env/genome/gencode/hg38/v38/gencode.v38.annotation.gtf"
    GENECODE_HG38_v38_ID2SYMBOL: "/public/home/lijf/env/genome/gencode/hg38/v38/tximport.geneid2symbol"
    GENECODE_HG38_v38_GENES: "/public/home/lijf/env/genome/gencode/hg38/v38/tximport.genes"
  sample_folder:
    FQDIR_RNA: "/public/home/lijf/projects/clinrep/data/rnaseq/fq"
    FQDIR_PANEL: "/public/home/lijf/projects/clinrep/data/panel/fq"
    FQDIR_WES: "/public/home/lijf/projects/clinrep/data/wes/fq"
    FQDIR_WGS: "/public/home/lijf/projects/clinrep/data/wgs/fq"
    FQDIR_IGH: "/public/home/lijf/projects/clinrep/data/igh/fq"
  varanno:
    KNOWN_SITES1: "/Users/ZYL/Documents/Project/Github/clinwdl/snakemake/WES/data/dbsnp_138.hg19.vcf"
    KNOWN_SITES2: "/Users/ZYL/Documents/Project/Github/clinwdl/snakemake/WES/data/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf"
    KNOWN_SITES1_38: "/public/home/lijf/env/genome/broad/hg38-v2/Homo_sapiens_assembly38.dbsnp138.vcf.gz"
    KNOWN_SITES2_38: "/public/home/lijf/env/genome/broad/hg38-v2/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"

softwares:
  BWA: "/public/home/lijf/env/miniconda3/envs/clindet/bin/bwa"
  bwa:
    conda: "clindet"
    mem:
      call: "/public/home/lijf/env/miniconda3/envs/clindet/bin/bwa mem "
      params: "-M "
      scratch: '2000'
      memory: '2000'
      time: '235'
      threads: 24
    aln:
      call: "/public/home/lijf/env/miniconda3/envs/clindet/bin/bwa aln "
      params: "-q 5 "
      scratch: '1000'
      memory: '1000'
      time: '235'
      threads: 24
    sampe:
      call: "/public/home/lijf/env/miniconda3/envs/clindet/bin/bwa sampe "
      params: ''
      scratch: '1000'
      mem: '1000'
      time: '235'
      threads: 24

  
  SAMTOOLS: "/public/home/lijf/env/miniconda3/envs/samtools114/bin/samtools"
  samtools:
    call: "/public/home/lijf/env/miniconda3/envs/samtools114/bin/samtools "
    conda: "samtools114"
    flagstat:
      scratch: '2000'
      mem: '4000'
      time: '20'
      threads: 1
      params: ''
    index:
      scratch: '2000'
      mem: '2000'
      time: '100'
      threads: 1
    mpileup:
      params: "-B -q 25 -Q 20 -d 100000"
      scratch: '8000'
      mem: '8000'
      time: '1400'
      threads: 1
    rmSecondary:
      scratch: '4000'
      mem: '4000'
      time: '235'
      threads: 1
    rmDuplicates:
      threads: 2
      scratch: '2000'
      mem: '2000'
      time: '235'
  
  GATK4: "/public/home/lijf/env/opt/bio/gatk/4.2.4.1/gatk"
  gatk4:
    call: "/public/ClinicalExam/lj_sih/projects/project_test2/analysis/cnv/cnv_call/gatk-4.2.6.1/gatk "
    MarkDuplicates:
      call: "/public/ClinicalExam/lj_sih/projects/project_test2/analysis/cnv/cnv_call/gatk-4.2.6.1/gatk MarkDuplicates "
    BaseRecalibrator:
      call: "/public/ClinicalExam/lj_sih/projects/project_test2/analysis/cnv/cnv_call/gatk-4.2.6.1/gatk BaseRecalibrator "
    ApplyBQSR:
      call: "/public/ClinicalExam/lj_sih/projects/project_test2/analysis/cnv/cnv_call/gatk-4.2.6.1/gatk ApplyBQSR "

  GATK3: "/public/home/lijf/env/opt/bio/gatk/3.8-0/GenomeAnalysisTK.jar"
  gatk3:
    call: "java -jar /public/home/lijf/env/opt/bio/gatk/3.8-0/GenomeAnalysisTK.jar"


  strelka:
    conda: "strelka"
    somatic:
      call:




  fastp:
    call: "/public/home/lijf/env/miniconda3/envs/fastp/bin/fastp"
    conda: "fastp"

  vcf2maf:
    call: "perl /public/ClinicalExam/lj_sih/projects/project_QC/env/vcf_maf/vcf2maf.pl "
    conda: "vep105"


  star:
    conda: "star279"
    index:
      hg38: "/public/home/lijf/env/genome/gencode/hg38/v38/star_index/2.7.9a"



  CLINREP_PRJ: "/public/home/lijf/projects/clinrep"
  JAVA: "/public/home/lijf/env/opt/jdk/1.8.0_201/bin/java"
  BWA: "/public/home/lijf/env/miniconda3/envs/clindet/bin/bwa"
  PICARD: "/public/home/lijf/env/opt/bio/picard/2.26.6/picard.jar"
  JELLYFISH: "/public/home/lijf/env/miniconda3/envs/km/bin/jellyfish"
  KM: "/public/home/lijf/env/miniconda3/envs/km/bin/km"
  KM_REFFA: "/public/home/lijf/env/opt/bio/km/data"
  IK6_REFFA: "/public/home/lijf/env/genome/salmon/ik6/v34"
  IK6_HEADER: "/public/home/lijf/env/genome/salmon/ik6/header"
  IK6_TNAME: "/public/home/lijf/env/genome/salmon/ik6/ikzf1"
  VARDICT_HOME: "/public/home/lijf/env/opt/bio/vardict"
  VARDICT_JAVA: "/public/home/lijf/env/opt/bio/vardictJava/1.8.3/bin/"
  VARSCAN2: "/public/home/lijf/env/opt/bio/varscan2/VarScan.v2.4.4.jar"
  SAMTOOLS: "/public/home/lijf/env/miniconda3/envs/samtools114/bin/samtools"
  LOFREQ: "/public/home/lijf/env/miniconda3/envs/clindet/bin/lofreq"
  LOFREQ_SOMATIC: "/public/home/lijf/env/miniconda3/envs/clindet/bin/lofreq2_somatic.py"
  SCALPEL: "/public/home/env/miniconda3/envs/clindet/bin/scalpel-discovery"
  GATK3: "/public/home/lijf/env/opt/bio/gatk/3.8-0/GenomeAnalysisTK.jar"

  VEP_BIN: "/public/home/lijf/env/miniconda3/envs/vep104/bin"
  VEP_DB: "/public/home/lijf/env/db/vep"
  SNPEFF: "/public/home/lijf/env/opt/bio/snpEff/5.0e/snpEff.jar"
  VCF2MAF: "/public/home/lijf/env/opt/bio/vcf2maf"
  MIXCR: "/public/home/lijf/env/opt/bio/mixcr/3.0.13/mixcr"
  VDJTOOLS: "/public/home/lijf/env/opt/bio/vdjtools/1.2.1/vdjtools-1.2.1.jar"
  TRUST4: "/public/home/lijf/env/opt/bio/trust4/run-trust4"
  FASTP: "/public/home/lijf/env/miniconda3/envs/fastp/bin/fastp"


